"""empty message

Revision ID: b0d39c65d2b7
Revises: 1f26daa5d5f7
Create Date: 2025-05-26 16:04:46.483704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d39c65d2b7'
down_revision: Union[str, None] = '1f26daa5d5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('area', sa.Integer(), nullable=True))
    op.add_column('houses', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('houses', sa.Column('garage', sa.Integer(), nullable=True))
    op.add_column('houses', sa.Column('total_basement', sa.Integer(), nullable=True))
    op.add_column('houses', sa.Column('bath', sa.Integer(), nullable=True))
    op.add_column('houses', sa.Column('overall_quality', sa.Integer(), nullable=True))
    op.add_column('houses', sa.Column('neighborhood', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('price', sa.Integer(), nullable=True))
    op.drop_column('houses', 'TotalBsmtSF')
    op.drop_column('houses', 'FullBath')
    op.drop_column('houses', 'OverallQual')
    op.drop_column('houses', 'GarageCars')
    op.drop_column('houses', 'GrLivArea')
    op.drop_column('houses', 'Neighborhood')
    op.drop_column('houses', 'YearBuilt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('YearBuilt', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('houses', sa.Column('Neighborhood', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('houses', sa.Column('GrLivArea', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('houses', sa.Column('GarageCars', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('houses', sa.Column('OverallQual', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('houses', sa.Column('FullBath', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('houses', sa.Column('TotalBsmtSF', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('houses', 'price')
    op.drop_column('houses', 'neighborhood')
    op.drop_column('houses', 'overall_quality')
    op.drop_column('houses', 'bath')
    op.drop_column('houses', 'total_basement')
    op.drop_column('houses', 'garage')
    op.drop_column('houses', 'year')
    op.drop_column('houses', 'area')
    # ### end Alembic commands ###
